name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congratulations! Thank you very much for opening the issue, continue opening issues in the future."
        pr-message: "Congratulations! Thank you very much for opening the PR, continue opening PRs in the future."
