name: python tests
run-name: ${{ github.actor }} push changes to ${{ github.head_ref || github.ref_name }} 🚀

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
on:
  push:
    paths:
      - '**.py'
    branches:
      - dev
      - master
  pull_request:
    paths:
      - '**.py'
    branches: 
      - dev
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          pytest